// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller

import { application } from "./application";

import TextareaAutogrow from "stimulus-textarea-autogrow";
application.register("textarea-autogrow", TextareaAutogrow);

import CharacterCounter from "stimulus-character-counter";
application.register("character-counter", CharacterCounter);

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import Dropdown from "./dropdown_controller";
application.register("dropdown", Dropdown);